

new_keys = {
"Antigua-and-Barbuda": "Antigua and Barb.",
"Bosnia-and-Herzegovina": "Bosnia and Herz.",
"British-Virgin-Islands": "British Virgin Is.",
"Burkina-Faso": "Burkina Faso",
"Cabo-Verde": "Cabo Verde",
"Cayman-Islands": "Cayman Is.",
"Cook-Islands": "Cook Is.",
"Costa-Rica": "Costa Rica",
"Cura&ccedil;ao": "Curaçao",
"Dominican-Republic": "Dominican Rep.",
"DPRK": "North Korea",
"DRC": "Dem. Rep. Congo",
"Equatorial-Guinea": "Eq. Guinea",
"El-Salvador": "El Salvador",
"Faeroe-Islands": "Faeroe Is.",
"Falkland-Islands": "Falkland Is.",
"French-Polynesia": "Fr. Polynesia",
"Hong-Kong": "Hong Kong",
"Isle-of-Man": "Isle of Man",
"Ivory-Coast": "Côte d'Ivoire",
"Marshall-Islands": "Marshall Is.",
"New-Caledonia": "New Caledonia",
"New-Zealand": "New Zealand",
"North-Macedonia": "Macedonia",
"Papua-New-Guinea": "Papua New Guinea",
"S-Korea": "South Korea",
"Saint-Helena": "Saint Helena",
"Saint-Kitts-and-Nevis": "St Kitts and Nevis",
"Saint-Lucia": "Saint Lucia",
"Saint-Martin": "St-Martin",
"Saint-Pierre-Miquelon": "St. Pierre and Miquelon",
"San-Marino": "San Marino",
"Sao-Tome-and-Principe": "São Tomé and Principe",
"Saudi-Arabia": "Saudi Arabia",
"Sierra-Leone": "Sierra Leone",
"Sint-Maarten": "Sint Maarten",
"Solomon-Islands": "Solomon Is.",
"South-Africa": "South Africa",
"South-Sudan": "S. Sudan",
"Sri-Lanka": "Sri Lanka",
"St-Barth": "St-Barthélemy",
"St-Vincent-Grenadines": "St. Vin. and Gren.",
"Trinidad-and-Tobago": "Trinidad and Tobago",
"Turks-and-Caicos": "Turks and Caicos Is.",
"UAE": "United Arab Emirates",
"UK": "United Kingdom",
"US-Virgin-Islands": "U.S. Virgin Is.",
"Vatican-City": "Vatican",
"Wallis-and-Futuna": "Wallis and Futuna Is.",
"Western-Sahara": "W. Sahara",
"USA": "United States of America"
}

